import type { Metadata } from "next";
import "./globals.css"
import { Roboto } from "next/font/google";
import LayoutProvider from "./_components/layoutProvider";

import GlobalContextProvider from "./_components/globalContextProvider";
import UserComponentData from "./_components/menu/userComponentData";
import { Locale } from "@/src/i18n-config";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params:{lang}
}: {
    children: React.ReactNode;
    params:{lang:Locale}
}) {
  return (
    <html lang={lang} className={roboto.className}>
      <body className="flex flex-row bg-[#F3F4F6] h-screen">
        
        <GlobalContextProvider>
          <LayoutProvider lang={lang}>{children}</LayoutProvider>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
