"use client";
import { usePathname } from "next/navigation";
import React from "react";
import GlobalStateProvider from "./globalStateProvider";
import SidbarMenu from "./sidbarMenu";
import Navbar from "./navbar";
import { Metadata } from "next";
import { Roboto } from "next/font/google";
import { SessionProvider } from "next-auth/react";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function LayoutProvider({ children }: { children: React.ReactNode }) {
  const path = usePathname();

  return (
    <SessionProvider>
      {/* SidbarMenu */}

      {path === "/signin" ? (
        <>{children}</>
      ) : (
        <GlobalStateProvider>
          <SidbarMenu />

          {/* Workspace */}

          <div className=" flex flex-col w-full ">
            <Navbar />

            <div className="w-full h-full p-4 sm:pt-10 sm:pl-5 overflow-y-scroll">
              {children}
            </div>
          </div>
        </GlobalStateProvider>
      )}
    </SessionProvider>
  );
}

export default LayoutProvider;
