import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SidbarMenu from "./_components/sidbarMenu";
import { Roboto } from "next/font/google";

import Navbar from "./_components/navbar";
import GlobalStateProvider from "./_components/globalStateProvider";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="flex flex-row bg-[#F3F4F6] h-screen">
        {/* SidbarMenu */}
        <GlobalStateProvider>
          <SidbarMenu />

          {/* Workspace */}

          <div className=" flex flex-col w-full ">
            <Navbar />

            <div className="w-full h-full p-4 sm:pt-10 sm:pl-5 overflow-y-scroll">
              
              {children}
            </div>
          </div>
        </GlobalStateProvider>
      </body>
    </html>
  );
}
