import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Roboto } from "next/font/google";
import LayoutProvider from "./_components/layoutProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const UserRoles = {
  admin: "Admin",
  client: "Client",
  manager: "Manger",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en" className={roboto.className}>
      <body className="flex flex-row bg-[#F3F4F6] h-screen">
        <LayoutProvider>{children}</LayoutProvider>
      </body>
    </html>
    /*  <html lang="en" className={roboto.className}>
      <body className="flex flex-row bg-[#F3F4F6] h-screen">
        
        <GlobalStateProvider>
          <SidbarMenu />

          

          <div className=" flex flex-col w-full ">
            <Navbar />

            <div className="w-full h-full p-4 sm:pt-10 sm:pl-5 overflow-y-scroll">
              
              {children}
            </div>
          </div>
        </GlobalStateProvider>
      </body>
    </html> */
  );
}
